`define FUNC_ADD 6'd0
`define FUNC_SUB 6'd1
`define FUNC_AND 6'd2
`define FUNC_ORR 6'd3
`define FUNC_NOT 6'd4
`define FUNC_TCP 6'd5
`define FUNC_SHL 6'd6
`define FUNC_SHR 6'd7
`define FUNC_WWD 6'd28
`define FUNC_JPR 6'd25
`define FUNC_JRL 6'd26
`define FUNC_HLT 6'd29

`define OPCODE_ADI 4'd4
`define OPCODE_ORI 4'd5
`define OPCODE_LHI 4'd6
`define OPCODE_LWD 4'd7
`define OPCODE_SWD 4'd8
`define OPCODE_BNE 4'd0
`define OPCODE_BEQ 4'd1
`define OPCODE_BGZ 4'd2
`define OPCODE_BLZ 4'd3
`define OPCODE_JMP 4'd9
`define OPCODE_JAL 4'd10
`define OPCODE_TYPE_R 4'd15

`define ALUOP_NONE 4'd0
`define ALUOP_ADD 4'd1
`define ALUOP_SUB 4'd2
`define ALUOP_SHL 4'd3
`define ALUOP_SHR 4'd4
`define ALUOP_AND 4'd5
`define ALUOP_ORR 4'd6
`define ALUOP_TCP 4'd7
`define ALUOP_NOT 4'd8
`define ALUOP_LHI 4'd9
`define ALUOP_ORI 4'd10
`define ALUOP_BNE 4'd11
`define ALUOP_BEQ 4'd12
`define ALUOP_BGZ 4'd13
`define ALUOP_BLZ 4'd14